"""
YouTube Transcript Helper
Used by FastAPI to fetch YouTube transcripts.
"""
from youtube_transcript_api import YouTubeTranscriptApi


def fetch_transcript(video_id: str, lang: str = "en") -> dict:
    if not video_id:
        return {"success": False, "error": "videoId is required"}

    try:
        transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
        transcript_list_items = list(transcript_list)
        if not transcript_list_items:
            print(f"No transcript list found for video: {video_id}")
            return {"success": False, "error": "No transcripts available for this video."}

        # Auto-detect language if requested
        if not lang or lang == "auto":
            available_langs = [t.language_code for t in transcript_list]
            if not available_langs:
                print(f"No available languages for video: {video_id}")
                return {"success": False, "error": "No transcripts available"}
            lang = available_langs[0]

        transcript = None
        tried_langs = []
        try:
            transcript = transcript_list.find_transcript([lang]).fetch()
            tried_langs.append(lang)
        except Exception as e:
            print(f"Failed to fetch transcript for language {lang}: {e}")
        if transcript is None and lang != "en":
            try:
                transcript = transcript_list.find_transcript(["en"]).fetch()
                lang = "en"
                tried_langs.append("en")
            except Exception as e2:
                print(f"Failed to fetch English transcript: {e2}")
        if transcript is None:
            available_langs = [t.language_code for t in transcript_list]
            auto_generated_langs = [t.language_code for t in transcript_list if getattr(t, 'is_generated', False)]
            if not available_langs:
                return {"success": False, "error": "No transcripts available"}
            auto_generated = auto_generated_langs[0] if auto_generated_langs else None
            fallback_lang = auto_generated if auto_generated else available_langs[0]
            try:
                transcript = transcript_list.find_transcript([fallback_lang]).fetch()
                lang = fallback_lang
                tried_langs.append(fallback_lang)
            except Exception as e3:
                print(f"Failed to fetch transcript for fallback language {fallback_lang}: {e3}")
                return {
                    "success": False,
                    "error": f"No transcript found for video {video_id}. Tried: {tried_langs}",
                    "availableLanguages": available_langs,
                    "autoGeneratedLanguages": auto_generated_langs,
                    "note": "Auto-generated transcripts may be listed but not always retrievable via the API."
                }

        if not transcript or len(transcript) == 0:
            print(f"Transcript is empty for video: {video_id}")
            return {"success": False, "error": "Transcript is empty."}

        segments = [
            {
                "text": entry.text,
                "start": entry.start,
                "duration": entry.duration,
            }
            for entry in transcript
        ]

        full_text = " ".join(entry.text for entry in transcript)

        return {
            "success": True,
            "transcript": segments,
            "fullText": full_text,
            "totalSegments": len(segments),
            "language": lang,
        }
    except Exception as exc:
        print(f"Exception occurred while fetching transcript for video {video_id}: {exc}")
        return {"success": False, "error": str(exc)}
