const { searchChunks } = require("../services/chatbot/retrievalService");

async function chatMessage(req, res) {
  try {
    const { message, resource_id, context } = req.body || {};

    if (!message || !resource_id) {
      return res.status(400).json({
        success: false,
        error: { message: "message and resource_id are required" },
      });
    }

    const embedding = Array(1536).fill(0.01);

    console.log("[Chat] resource:", resource_id, "context:", context);

    const chunks = await searchChunks({ embedding, resource_id, context });

    return res.json({
      success: true,
      answer: "Answer will be generated by LLM later",
      chunks,
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      error: { message: err.message || "Internal error" },
    });
  }
}

module.exports = { chatMessage };
